fixtures:
  symlinks:
    rjil: "#{source_dir}"
  repositories:
    haproxy:
      repo: git://github.com/puppetlabs/puppetlabs-haproxy
      ref: 1.0.0
    inifile:
      repo: git://github.com/puppetlabs/puppetlabs-inifile.git
      ref: 41e2ddbc1cd861247e57d16b778cbe891602f509
    etcd:
      repo: git://github.com/JioCloud/puppet-etcd.git
      ref: 74efce9cbd0f854b33111dc0ffa72b5a349e3f8f
    openstack_extras:
      repo: https://github.com/bodepd/puppet-openstack_extras
    heat:
      repo: https://github.com/stackforge/puppet-heat
    nova:
      repo: https://github.com/stackforge/puppet-nova
    glance:
      repo: https://github.com/stackforge/puppet-glance
    keystone:
      repo: https://github.com/stackforge/puppet-keystone
    cinder:
      repo: https://github.com/stackforge/puppet-cinder
    neutron:
      repo: https://github.com/stackforge/puppet-neutron
    memcached:
      repo: git://github.com/saz/puppet-memcached
      ref: fee24ce
    ssh:
      repo: https://github.com/saz/puppet-ssh
      ref: v2.3.6
    sysctl:
      repo: https://github.com/duritong/puppet-sysctl
      ref: 3b027e816818f2c1086075038ac9b4af1cadbc24
    cassandra:
      repo: https://github.com/msimonin/puppet-cassandra
      ref: 'puppet-cassandra-0.6.0'
    staging:
      repo: https://github.com/nanliu/puppet-staging
      ref: 0.4.0
    apache:
      repo: https://github.com/puppetlabs/puppetlabs-apache
      ref: 1.0.1
    apt:
      repo: https://github.com/puppetlabs/puppetlabs-apt
      ref: 1.5.0
    cinder:
      repo: https://github.com/stackforge/puppet-cinder
      ref: 4.0.0
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat
      ref: 1.1.0
    glance:
      repo: https://github.com/stackforge/puppet-glance
      ref: 4.0.0
    keystone:
      repo: https://github.com/stackforge/puppet-keystone
      ref: 4.0.0
    mysql:
      repo: https://github.com/puppetlabs/puppetlabs-mysql
      ref: 2.2.3
    neutron:
      repo: https://github.com/stackforge/puppet-neutron
      ref: 4.1.0
    nova:
      repo: https://github.com/stackforge/puppet-nova
      ref: 4.0.0
    rabbitmq:
      repo: https://github.com/puppetlabs/puppetlabs-rabbitmq
      ref: 4.0.0
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib
      ref: 4.2.2
    vswitch:
      repo: https://github.com/stackforge/puppet-vswitch
      ref: 0.3.0
    puppet:
      repo: https://github.com/stephenrjohnson/puppetmodule
      ref: 1.0.0
    ntp:
      repo: https://github.com/puppetlabs/puppetlabs-ntp
      ref: 3.0.1
